=== kmedina47/assignment-1--databases--cs-365--fall-2024/xml/student.dtd
<!-- ===================================================================
  The student-information element is the root element of the student
  database and must contain one or more student elements. This is
  evident with the placement of the + metacharacter after (student).

  Note: This element does not allow for parsed character data nor simple
  character data.
  ================================================================== -->
<!ELEMENT student-information (student)+>  <!-- student-information is the root element -->

<!-- ===================================================================
  Note: The ? metacharacter associated with the 'middle-name' and
  'preferred-name' elements represents the optional characteristic of
  these particular elements.
  ================================================================== -->
<!ELEMENT student                 (first-name,middle-name?,last-name,preferred-name?,studentID,email,phone,academic-status,GPA,major,minor,enrollment-status,advisor,initial-enrollment-date,graduation-date)> <!-- contains all the parsed character data associated with the 'student' element -->
<!ELEMENT first-name              (#PCDATA)> <!-- The student's first name is required -->
<!ELEMENT middle-name             (#PCDATA)> <!-- The student's middle name is optional -->
<!ELEMENT last-name               (#PCDATA)> <!-- The student's last name is required -->
<!ELEMENT preferred-name          (#PCDATA)> <!-- The student's preferred name is optional -->
<!ELEMENT studentID               (#PCDATA)> <!-- The student's student ID is required -->
<!ELEMENT email                   (#PCDATA)> <!-- The student's email address is required -->
<!ELEMENT phone                   (#PCDATA)> <!-- The student's phone number is required -->
<!ELEMENT academic-status         (#PCDATA)> <!-- The student's academic-status is required -->
<!ELEMENT GPA                     (#PCDATA)> <!-- The student's GPA is required -->
<!ELEMENT major                   (#PCDATA)> <!-- The student's major is required -->
<!ELEMENT minor                   (#PCDATA)> <!-- The student's minor is required -->
<!ELEMENT enrollment-status       (#PCDATA)> <!-- The student's enrollment status is required -->
<!ELEMENT advisor                 (#PCDATA)> <!-- The student's advisor name is required -->
<!ELEMENT initial-enrollment-date (#PCDATA)> <!-- The student's initial enrollment date is required -->
<!ELEMENT graduation-date         (#PCDATA)> <!-- The student's graduation date is required -->

<!ATTLIST student
          name CDATA #REQUIRED> <!-- The 'student' element has the 'name' attribute, which is required and contains character data. -->

=== kmedina47/assignment-1--databases--cs-365--fall-2024/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE student-information SYSTEM "student.dtd">

<student-information>
  <student name="Student 1">
    <first-name>Gordon</first-name>
    <middle-name>Matthew</middle-name>
    <last-name>Summer</last-name>
    <preferred-name>Sting</preferred-name>
    <studentID>1234567</studentID>
    <email>sting@thepolice.com</email>
    <phone>212.123.4567</phone>
    <academic-status>first year</academic-status>
    <GPA>4.0</GPA>
    <major>Music</major>
    <minor>English</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Andy Summers</advisor>
    <initial-enrollment-date>08-25-1969</initial-enrollment-date>
    <graduation-date>05-01-1973</graduation-date>
  </student>
  <student name="Student 2">
    <first-name>Kim</first-name>
    <middle-name />
    <last-name>Thayil</last-name>
    <preferred-name />
    <studentID>4567890</studentID>
    <email>kim@soundgarden.com</email>
    <phone>206.123.4567</phone>
    <academic-status>second year</academic-status>
    <GPA>3.0</GPA>
    <major>Philosophy</major>
    <minor>Music</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Chris Cornell</advisor>
    <initial-enrollment-date>08-25-1978</initial-enrollment-date>
    <graduation-date>05-01-1982</graduation-date>
  </student>
  <student name="Student 3">
    <first-name>Saul</first-name>
    <middle-name />
    <last-name>Hudson</last-name>
    <preferred-name>Slash</preferred-name>
    <studentID>8302438</studentID>
    <email>slash@gnr.com</email>
    <phone>213.456.8392</phone>
    <academic-status>fourth year</academic-status>
    <GPA>2.0</GPA>
    <major>Music</major>
    <minor>Criminal Justice</minor>
    <enrollment-status>part-time</enrollment-status>
    <advisor>Axl Rose</advisor>
    <initial-enrollment-date>08-25-1983</initial-enrollment-date>
    <graduation-date>05-01-1987</graduation-date>
  </student>
  <student name="Student 4">
    <first-name>Emily</first-name>
    <middle-name />
    <last-name>Kokal</last-name>
    <preferred-name />
    <studentID>2983928</studentID>
    <email>emily@warpaint.com</email>
    <phone>213.123.7654</phone>
    <academic-status>third year</academic-status>
    <GPA>3.8</GPA>
    <major>Political Science</major>
    <minor>Law</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jenny Lee Lindberg</advisor>
    <initial-enrollment-date>08-25-1998</initial-enrollment-date>
    <graduation-date>05-01-2002</graduation-date>
  </student>
  <student name="Student 5">
    <first-name>Mike</first-name>
    <middle-name />
    <last-name>Inez</last-name>
    <preferred-name />
    <studentID>7645726</studentID>
    <email>mike@aic.com</email>
    <phone>213.444.3323</phone>
    <academic-status>second year</academic-status>
    <GPA>4.0</GPA>
    <major>Business Management</major>
    <minor>Math</minor>
    <enrollment-status>full-time</enrollment-status>
    <advisor>Jerry Cantrell</advisor>
    <initial-enrollment-date>08-25-1984</initial-enrollment-date>
    <graduation-date>05-01-1988</graduation-date>
  </student>
</student-information>
